### ISSUE TITLE
chat-image.svelte error

### ISSUE THREAD

**Issue by waelhosn** [SciSharp/BotSharp-UI#55]
The message object being returned is from a specific function within the agent and it is of not type string

https://github.com/SciSharp/BotSharp-UI/blob/5444a229fe4a08cc8984a28aff85438f9ec00290/src/routes/chat/%5BagentId%5D/%5BconversationId%5D/chatImage/chat-image.svelte#L8

**Comment by Oceania2018** [comment]
Can you try to pull latest code and test it again?

**Comment by waelhosn** [comment]
The conversation window is empty when trying to render it. Also have you changed anything in the architecture? Because I think there an issue with the routing and messages being returned @Oceania2018

**Comment by Oceania2018** [comment]
No changes in terms of architecture. Any error message you can find from console?

**Comment by waelhosn** [comment]
This is occurring when initiating a new conversation with one of the agents
![image](https://github.com/SciSharp/BotSharp-UI/assets/25593316/9db137f6-6e72-413e-bfda-81f1d35fbe98)

When trying the send message API on postman, I am getting the same prompt message over and over. The behavior of routing to a function or responding is very different than how it was. I didn't change anything in the instructions or functions that I had but for some reason after your recent commits (within the last 10 days). The agent stopped behaving like it used to, it is as if it has no reasoning anymore.

**Comment by waelhosn** [comment]
It seems like this error occurs when receiving feedback or a message from a function. Whenever the agent doesn't route to a function, the message is rendered fine. However, when its routed to a function the output is then causing issues and resulting in the loading dots to get stuck. @Oceania2018 

<img width="508" alt="image" src="https://github.com/SciSharp/BotSharp-UI/assets/25593316/d0bfc741-b94d-4aad-af35-3f40b87ae0d6">

<img width="940" alt="image" src="https://github.com/SciSharp/BotSharp-UI/assets/25593316/247d7e7a-1ba1-45ad-8e69-d5d6833fbc3c">

**Comment by Oceania2018** [comment]
> This is occurring when initiating a new conversation with one of the agents ![image](https://private-user-images.githubusercontent.com/25593316/307052568-9db137f6-6e72-413e-bfda-81f1d35fbe98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg3NjEsIm5iZiI6MTcwODY4ODQ2MSwicGF0aCI6Ii8yNTU5MzMxNi8zMDcwNTI1NjgtOWRiMTM3ZjYtNmU3Mi00MTNlLWJmZGEtODFmMWQzNWZiZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZWYyOGEwOWQ1NjkyMjAyMzkyMGJmYzYzODM2M2I2MWJiZTI1YmRiYWEzZjFjZGJmMjBlMGIxY2FmOWNkZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uwq2jYj1fvQU5o_CKxRfrKkU7AEmG1lP6m9BXB8IDWE)
> 
> When trying the send message API on postman, I am getting the same prompt message over and over. The behavior of routing to a function or responding is very different than how it was. I didn't change anything in the instructions or functions that I had but for some reason after your recent commits (within the last 10 days). The agent stopped behaving like it used to, it is as if it has no reasoning anymore.

The url is changed to ‘/user/me’.

**Comment by Oceania2018** [comment]
> It seems like this error occurs when receiving feedback or a message from a function. Whenever the agent doesn't route to a function, the message is rendered fine. However, when its routed to a function the output is then causing issues and resulting in the loading dots to get stuck. @Oceania2018
> 
> <img alt="image" width="508" src="https://private-user-images.githubusercontent.com/25593316/307101750-d0bfc741-b94d-4aad-af35-3f40b87ae0d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg3NjEsIm5iZiI6MTcwODY4ODQ2MSwicGF0aCI6Ii8yNTU5MzMxNi8zMDcxMDE3NTAtZDBiZmM3NDEtYjk0ZC00YWFkLWFmMzUtM2Y0MGI4N2FlMGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZjEwOTM3MDY5MDJiZTEwOWY2MmVkMjIxNjZkMGI0OGY5ZGQwMjgyOWM5ZTM4MTY3Y2JjZDRkY2YyMjc2ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vRqIGb7AhvdtoMEM3TKxrGOYmZ-5xS5h_bi4DIB1SSY"> <img alt="image" width="940" src="https://private-user-images.githubusercontent.com/25593316/307102252-247d7e7a-1ba1-45ad-8e69-d5d6833fbc3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODg3NjEsIm5iZiI6MTcwODY4ODQ2MSwicGF0aCI6Ii8yNTU5MzMxNi8zMDcxMDIyNTItMjQ3ZDdlN2EtMWJhMS00NWFkLThlNjktZDVkNjgzM2ZiYzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExNDEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNWY4OGQwNzJmZTA1ODJmNWM5Zjg2MWIxNjJiZDdmN2Y5ZDhlNjE5NDhkMzQ3MmIxYWJiNWRmYTEwNjRmMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5TtzSkdJ41M2tCNY3U3nXfzq1GZazXRv1XX6g58WQ58">

This bug is fixed, can you pull latest to test? BotSharp and UI both need to pull.

**Comment by waelhosn** [comment]
@Oceania2018 still same issue.

**Comment by Oceania2018** [comment]
Can you provide the backend exception log?

**Comment by waelhosn** [comment]
The only exception is on the front-end side which I shared previously

**Comment by Oceania2018** [comment]
I think this [fix ](https://github.com/SciSharp/BotSharp/commit/8a714f726f74d00fab43e9d1b1a9c9205fefcc04)will help you out.

**Comment by waelhosn** [comment]
@Oceania2018 still getting this error

chat-image.svelte:8 Uncaught (in promise) TypeError: ctx[0].data.includes is not a function
    at create_fragment (chat-image.svelte:8:36)
    at init (chunk-INGULII4.js?v=398bdd24:2203:35)
    at new Chat_image (chat-image.svelte:5:20)
    at createProxiedComponent (svelte-hooks.js?v=398bdd24:341:9)
    at new ProxyComponent (proxy.js?v=398bdd24:242:7)
    at new Proxy<Chat-image> (proxy.js?v=398bdd24:349:11)
    at Array.create_else_block (chat-box.svelte:639:37)
    at create_each_block_1 (chat-box.svelte:597:52)
    at Object.update [as p] (chat-box.svelte:593:15)
    at Object.update [as p] (chat-box.svelte:587:15)

![image](https://github.com/SciSharp/BotSharp-UI/assets/25593316/15293f99-9646-45bc-96da-a914fe6b9888)

After refreshing the page, the response is rendered:

![image](https://github.com/SciSharp/BotSharp-UI/assets/25593316/e0bedafe-6bf9-43d7-828c-d2d6313ec882)

**Comment by Oceania2018** [comment]
It's been fixed.
![image](https://github.com/SciSharp/BotSharp-UI/assets/1705364/b07827be-9e16-4769-91fb-73c48a04fada)

**Comment by waelhosn** [comment]
Working fine!
